### ISSUE TITLE
update to gitbook v3

### ISSUE THREAD

**Issue by noerw** [piranna/gitbook-plugin-printlinks#2]
would be nice if this great plugin would work again with current gitbook v3 or soon to be released gitbook v4

**Comment by piranna** [comment]
I have not used it in a long time, but if you want to update it, pull-requests are welcome :-)

**Comment by noerw** [comment]
did some work in #3. should work with gitbook 3.2.x again, but i am not really familiar with your code or the gitbook API

**Comment by noerw** [comment]
adapting to v4 may be done when this version is [released](https://github.com/GitbookIO/gitbook/releases)
